spring:
  redis:
    host: xxx.xxx.xxx.xxx
    port: 6379
    password: xxxxxx
    lettuce:
      pool:
        max-active: 8  #\u6700\u5927\u8FDE\u63A5
        max-idle: 8   #\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5
        min-idle: 0   #\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5
        max-wait: 100ms #\u8FDE\u63A5\u7B49\u5F85\u65F6\u95F4
