server:
  port: 8081

spring:
  application:
    name: redis-case
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rediscase?useSSL=false&serverTimezone=UTC
    username: root
    password: 806823
  # Redis
  redis:
    host: ×××.×××.×××.××
    port: 6379
    password: ××××××
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms

  jackson:
    default-property-inclusion: NON_NULL

mybatis-plus:
  type-aliases-package: com.lt.learningredis.entity

logging:
  level:
    com.lt.learningredis: debug